services:
  - type: web
    name: si pintar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: KOLOSAL_API_KEY
        sync: false